beans:
  clickup:
    list_id: "901112937048"
    status_mapping:
      draft: "not started"
      todo: "not started"
      in-progress: "in progress"
      completed: "completed"
      scrapped: "completed"
    custom_fields:
      bean_id: "a0b0c69a-d036-4031-9deb-4ecc4cfa3e55"
      created_at: "d3adc5e1-eedf-46e0-b5d5-a4dce3a0666b"
    users:
      kyle: 87372475
      lea: 87368252
      jason: 87367200
      jon: 144210928
      michaelc: 87342219
      alisa: 81565958
      jacks: 81553409
      anthony: 81488357
      emily: 81485023
      justin: 81485022
      shaugnessy: 81468547
      keagan: 81466398
      joel: 81459578
      martin: 114103627